### ISSUE TITLE
Fix regolith for ubuntu 22.04

### ISSUE THREAD

**Issue by konradmalik** [konradmalik/infra#3]
https://launchpad.net/~regolith-linux/+archive/ubuntu/stable

**Comment by g85606572** [comment]
error after upgrade to ubuntu 22.04 :(

**Comment by konradmalik** [comment]
Regolith still does not provide packages for 22.04 it seems. The whole repo works when gui_apps=false

**Comment by konradmalik** [comment]
https://github.com/regolith-linux/regolith-desktop/issues/638#issuecomment-1123181707

**Comment by konradmalik** [comment]
regolith 2.0 which supports jammy added in 7d80dbd45e3c16dd42482e633256ec423260d088
